import SwiftUI

enum AppLanguage: String, CaseIterable {
    case system = ""
    case english = "en"
    case russian = "ru"
    case ukrainian = "uk"

    var displayName: String {
        switch self {
        case .system: return "System"
        case .english: return "English"
        case .russian: return "Русский"
        case .ukrainian: return "Українська"
        }
    }

    var locale: Locale {
        switch self {
        case .system: return Locale.current
        case .english: return Locale(identifier: "en")
        case .russian: return Locale(identifier: "ru")
        case .ukrainian: return Locale(identifier: "uk")
        }
    }
}

struct AppLanguageKey: EnvironmentKey {
    static let defaultValue: String = ""
}

extension EnvironmentValues {
    var appLanguage: String {
        get { self[AppLanguageKey.self] }
        set { self[AppLanguageKey.self] = newValue }
    }
}

enum L {
    static func string(_ key: String, language: String) -> String {
        let lang = language.isEmpty ? (Locale.current.language.languageCode?.identifier ?? "en") : language
        let dict = strings[lang] ?? strings["en"]!
        return dict[key] ?? strings["en"]?[key] ?? key
    }

    /// Returns localized duration string (e.g. "45m", "1h 20m").
    static func formattedDuration(minutes: Int, language: String) -> String {
        if minutes < 60 {
            return String(format: string("duration_min", language: language), minutes)
        }
        let h = minutes / 60
        let m = minutes % 60
        return m > 0
            ? String(format: string("duration_h_min", language: language), h, m)
            : String(format: string("duration_h", language: language), h)
    }

    /// Returns localized activity name for built-in activities; returns original name for custom activities.
    static func activityName(_ name: String, language: String) -> String {
        let key = "activity_\(name.lowercased().replacingOccurrences(of: " ", with: "_"))"
        let translated = string(key, language: language)
        return translated != key ? translated : name
    }

    private static let strings: [String: [String: String]] = [
        "en": [
            "seeds": "Seeds",
            "rejoy_button_hint_title": "What is Rejoy?",
            "rejoy_button_hint_body": "This button activates your seeds. Before tapping it, you've only created them. Tap Rejoy to activate them.",
            "rejoy_button_hint_got_it": "Got it",
            "seeds_for": "Seeds for",
            "seeds_planted": "seeds planted",
            "today": "Today",
            "total": "total",
            "yesterday": "Yesterday",
            "choose_day": "Choose Day",
            "done": "Done",
            "today_timeline": "Today's Activity",
            "yesterday_timeline": "Yesterday's Activity",
            "timeline": "Activity",
            "no_sessions": "No sessions yet. Tap Start to begin.",
            "no_sessions_day": "No sessions this day.",
            "empty_state_title": "Your timeline is ready",
            "empty_state_subtitle": "Tap the orange button below to start your first activity",
            "rejoy": "Rejoy",
            "rejoyed": "Rejoyed",
            "rejoyed_exclamation": "rejoyed!",
            "ongoing": "Ongoing",
            "activity": "Activity",
            "activity_meditation": "Meditation",
            "activity_yoga": "Yoga",
            "activity_walking": "Walking",
            "activity_running": "Running",
            "activity_work": "Work",
            "activity_cooking": "Cooking",
            "activity_reading": "Reading",
            "activity_family": "Family",
            "activity_study": "Study",
            "seeds_count": "%d seeds",
            "seeds_count_formatted": "%@ seeds",
            "share_activity": "Share Activity",
            "share_to": "Share to",
            "save_image": "Save",
            "copy_image": "Copy",
            "copied": "Copied",
            "copy_sticker_hint": "The image will be copied with transparent background. It will be in the clipboard — you can go to any messenger or app and paste it there.",
            "more": "More",
            "close": "Close",
            "photo_library_required": "Photo Library Required",
            "photo_library_required_message": "Allow access to save the sticker to your photos.",
            "settings": "Settings",
            "profile": "Profile",
            "permissions": "Permissions",
            "app_language": "App Language",
            "language": "Language",
            "language_description": "Choose the language for the app interface.",
            "recognition_language": "Recognition language",
            "voice": "Voice",
            "voice_footer": "Choose the language you speak when recording your dedication. Select Russian explicitly if automatic doesn't transcribe correctly.",
            "automatic_russian": "Automatic (Russian first)",
            "russian": "Russian",
            "english": "English",
            "ukrainian": "Ukrainian",
            "seeds_per_second": "Seeds per second",
            "seeds_this_month": "Seeds this month",
            "seeds_stats": "Seeds stats",
            "total_seeds": "Total Seeds",
            "month_seeds_format": "%@ Seeds",
            "monthly_seeds_planted": "Monthly seeds planted",
            "seeds_for_month_year_format": "Seeds for %@",
            "time_for_meditation": "Time for meditation",
            "how_to_meditate": "How to meditate?",
            "seeds_description": "Every second of dedication creates causes (\"seeds\") that carry forward. What you do is never neutral.",
            "default": "Default",
            "activity_types": "Activity Types",
            "add_activity": "Add Activity",
            "edit_activity": "Edit Activity",
            "restore_activity": "Restore",
            "delete_activity_confirm": "Remove this activity?",
            "about": "About",
            "version": "Version 1.0",
            "about_description": "Track your practice. Plant seeds with every moment of dedication.",
            "microphone": "Microphone",
            "record_voice": "Record voice dedications",
            "speech_recognition": "Speech Recognition",
            "transcribe_dedication": "Transcribe your dedication",
            "notifications": "Notifications",
            "daily_reminder": "Optional daily reminder",
            "notifications_nudges_message": "Receive nudges from friends and daily reminders",
            "enable": "Enable",
            "enabled": "Enabled",
            "denied": "Denied",
            "not_set": "Not set",
            "unknown": "Unknown",
            "open_settings": "Open Settings",
            "notifications_required": "Notifications Required",
            "notifications_required_message": "Allow notifications in Settings > Rejoy > Notifications for the meditation alarm to work.",
            "permissions_intro": "Enable these for the best experience. You can change them later in Settings.",
            "skip_for_now": "Skip for now",
            "continue_as_guest": "Continue as Guest",
            "sign_in_with_apple": "Sign in with Apple",
            "login_legal_markdown": "By proceeding to use Rejoy, you agree to our [**terms of use**](%@) and acknowledge that you have read our [**privacy policy**](%@).",
            "watch_stories_again": "Watch stories again",
            "replay_intro": "Replay intro",
            "rej": "Rejoy",
            "start_activity": "Start Activity",
            "cancel": "Cancel",
            "error": "Error",
            "dedication": "Dedication",
            "dedication_default": "May this dedication benefit all beings.",
            "record_dedication": "Record your dedication",
            "save_seeds": "Save Seeds",
            "microphone_unavailable": "Microphone or voice not available",
            "type_dedication": "Type your dedication below",
            "tap_to_record": "Tap to record",
            "tap_to_stop": "Tap to stop",
            "adjust_duration": "Adjust Duration",
            "adjust_duration_hint": "Add or remove minutes below",
            "duration_adjust_min": "- %d min",
            "duration_adjust_plus": "+ %d min",
            "session": "Session",
            "delete_session": "Delete Session",
            "delete_activity": "Delete Activity",
            "cannot_undo": "This cannot be undone.",
            "delete": "Delete",
            "name": "Name",
            "icon": "Icon",
            "save": "Save",
            "next": "Next",
            "save_changes": "Save Changes",
            "time": "Time",
            "delete_session_confirm": "Delete Session?",
            "pause": "Pause",
            "resume": "Resume",
            "stop": "Stop",
            "seeds_planted_count": "%d seeds planted",
            "duration_min": "%dm",
            "duration_h": "%dh",
            "duration_h_min": "%dh %dm",
            "rejoy_meditation_time": "Rejoy Meditation",
            "rejoy_meditation_enable": "Enable",
            "rejoy_meditation_description": "Set a daily time for Rejoy meditation. Allow notifications when prompted. Rejoy buttons unlock after this time.",
            "rejoy_meditation_prompt_title": "Set your Rejoy time",
            "rejoy_meditation_prompt_subtitle": "Unlock Rejoy buttons after your daily meditation. Tap to set.",
            "test_notification": "Test notification (in 5 sec)",
            "accumulating_potential": "Accumulating...",
            "ready_at": "Ready at %@",
            "rejoy_in_h": "Rejoy in %dh",
            "rejoy_in_m": "Rejoy in %dm",
            "accumulating_explanation_title": "Rejoy unlocks after meditation",
            "accumulating_explanation_body": "Rejoy buttons unlock after your daily meditation time. You can change the time in Settings.",
            "rejoy_button": "Rejoy",
            "accumulating_sheet_title": "Unlock after your Rejoy Meditation",
            "accumulating_sheet_explainer": "Rejoy is a tactile way to finalize your good things one by one. After your Rejoy Meditation, tap each session to once again remember all the good things and feel happy at the end of the day.",
            "understood": "Understood",
            "unlock_in_h": "in %dh",
            "unlock_in_h_m": "in %dh %dm",
            "unlock_in_m": "in %dm",
            "rejoy_meditation_carousel_title": "Rejoy Meditation",
            "rejoy_meditation_slide_1_title": "Remember your good deeds.",
            "rejoy_meditation_slide_1_desc": "Replay in your mind all the good deeds and moments of care you have shown today.",
            "rejoy_meditation_slide_2_title": "Feel the circles of influence.",
            "rejoy_meditation_slide_2_desc": "Imagine the joy of the people you helped, and how their mood is passed on to others.",
            "rejoy_meditation_slide_3_title": "Realize your generosity.",
            "rejoy_meditation_slide_3_desc": "Remember how you shared your time, attention, support, or provided help.",
            "rejoy_meditation_slide_4_title": "Gratitude practice.",
            "rejoy_meditation_slide_4_desc": "Thank the world for life itself, your loved ones, your opportunities, and simple blessings.",
            "rejoy_meditation_slide_5_title": "Time to blossom.",
            "rejoy_meditation_slide_5_desc": "Feel how joy activates your good deeds, watering them like a well-kept garden.",
            "learn_more_rejoy_meditation": "How to do the meditation?",
            "skip": "Skip",
            "sangha": "Group",
            "create_sangha": "Create group",
            "join_sangha": "Join a Group",
            "join_by_code": "Join with code",
            "sangha_name": "Group name",
            "invite_code": "Invite code",
            "invite": "Invite",
            "invite_members": "Invite members",
            "invite_link_description": "Share this link so others can join your Group",
            "invite_message": "Join my Group in Rejoy!\n\n1. Open Rejoy and go to Profile → Settings\n2. Tap Visibility & Groups\n3. Turn on the switcher and enter this code:\n\n%@",
            "join_sangha_code_hint": "Enter the 6-character code shared with you by a Group member.",
            "profile_visibility": "Visibility & Groups",
            "private": "Private",
            "private_profile_description": "Your activity won't appear on the home screen for group members. Turn on to share your progress.",
            "public": "Public",
            "public_profile": "Public Profile",
            "groups": "Groups",
            "group_members_count": "%d members",
            "profile_visibility_invite_title": "Join a Group",
            "profile_visibility_invite_description": "A group lets you see each other's activity on the home screen. Ask a group member for the 6-character invite code.",
            "insert_invite_code": "Insert invite code",
            "switch_to_private_confirm": "Switch to private?",
            "switch_to_private_confirm_message": "You'll be hidden from others in the group. They won't see your activity until you turn visibility back on.",
            "invite_to_group": "Invite to group",
            "pause_my_visibility": "Pause my visibility",
            "leave_group": "Leave group",
            "leave_group_confirm": "Leave this group?",
            "leave_group_confirm_message": "You'll be removed from the group. You can rejoin anytime with an invite code.",
            "active_now": "Active now",
            "karma_partners": "Karma Partners",
            "seeds_accumulating": "accumulating",
            "sangha_empty_state": "Join a group to see others' activity",
            "push_to_activity_button": "Give a little push",
            "partner": "Partner",
            "nudge_permission_prompt_title": "Receive nudges from friends",
            "nudge_permission_prompt_message": "Enable notifications to get nudges when you're not in the app.",
            "nudge_sent": "Nudge sent!",
            "nudge_notification_title": "%@ is rooting for you!",
            "nudge_notification_subtitle": "Start an activity to plant seeds.",
            "continue": "Continue",
            "account": "Account",
            "log_out": "Log Out",
            "log_out_confirm": "Log Out?",
            "log_out_confirm_message": "Your local data will be kept. You can sign in again anytime.",
            "achievement_save": "Got it",
            "achievement_unlocked": "Unlocked!",
            "achievement_unlocked_on": "Unlocked on",
            "achievement_section_title": "Rewards",
            "achievement_empty_state": "Complete all Rejoy buttons to unlock rewards",
            "rewards_view_all": "View all",
            "rewards_gallery_title": "All rewards",
            "rewards_achieved_progress": "Achieved %1$lld/%2$lld",
            "rewards_explainer_title": "How rewards work",
            "rewards_explainer_body": "Finish your day by tapping Rejoy on each activity when you’re done. Each day, one reward can unlock at random when you complete your Rejoys. Your collection grows over time — keep finishing activities and celebrating them with Rejoy to earn every badge. The date under a badge is when you last unlocked it on this device.",
            "rewards_unlock_date_unknown": "Date unavailable",
            "share_app": "Share Rejoy",
            "share_app_message": "Hi, join Rejoy! Track your meditation and dedication. Plant seeds with every moment of mindfulness. Try the beta:",
            "share_app_message_with_seeds": "Hey! Here's how many seeds gathered for me this month: %@ 🌱\nJoin Rejoy and try the beta:\n",
            "seeds_field_empty": "Plant seeds with meditation",
            "what_is_seeds": "What are seeds?",
            "what_is_seeds_explainer": "Learn how mental imprints accumulate and shape your reality. Based on Buddhist psychology and the Diamond Cutter.",
            "seeds_info_slide_1_title": "Mental imprints.",
            "seeds_info_slide_1_desc": "Every moment of experience plants \"seeds\" in the subconscious. These imprints are never neutral — they accumulate and shape how you perceive the world and what life brings you.",
            "seeds_info_slide_2_title": "65 seeds per second.",
            "seeds_info_slide_2_desc": "According to Buddhist texts (Abhidharmakosha), the mind processes about %@ mental moments per second. Each moment of attention leaves an imprint. What you focus on matters.",
            "seeds_info_slide_3_title": "They add up fast.",
            "seeds_info_slide_3_desc": "Per minute: %@ seeds. Per hour: %@. Per full day: %@. Your daily actions create a vast field of causes that will bear fruit in the future.",
            "seeds_info_slide_4_title": "Seeds shape reality.",
            "seeds_info_slide_4_desc": "Like a white screen, reality is neutral. Your past seeds project onto it. Good deeds plant good seeds — for abundance, health, harmony. What you do today becomes tomorrow's experience.",
            "seeds_info_slide_5_title": "Water your seeds.",
            "seeds_info_slide_5_desc": "Evening Rejoy meditation \"waters\" your good seeds with joy. This seals them and helps them grow. A small good deed, remembered with happiness, doubles in strength each day.",
            "unfinished_rejoy_reminder_title": "Your seeds from yesterday are waiting",
            "unfinished_rejoy_reminder_body": "You completed some activities yesterday. Tap Rejoy to water those seeds and feel the joy of what you did.",
            "unfinished_rejoy_reminder_action": "Rejoy now",
            "unfinished_rejoy_reminder_skip": "Later",
            "how_to_use_rejoy": "How to use Rejoy?",
            "how_to_use_rejoy_explainer": "A quick guide to track activities, activate seeds, and share your progress.",
            "how_to_use_slide_1_title": "Start an activity",
            "how_to_use_slide_1_desc": "Tap the button and choose your activity — meditation, yoga, work, or family.",
            "how_to_use_slide_2_title": "Seeds are growing",
            "how_to_use_slide_2_desc": "Every second of your activity plants karmic seeds.",
            "how_to_use_slide_3_title": "Give it meaning",
            "how_to_use_slide_3_desc": "After finishing, record a short dedication and give your action a deeper purpose.",
            "how_to_use_slide_4_title": "Set Rejoy time",
            "how_to_use_slide_4_desc": "Choose when your seeds will be activated through meditation.",
            "how_to_use_slide_5_title": "Activate your seeds",
            "how_to_use_slide_5_desc": "Rejoy your activities to turn seeds from orange into green.",
            "how_to_use_slide_6_title": "Share your practice",
            "how_to_use_slide_6_desc": "Create beautiful badges and share your activities with friends.",
            "how_to_use_slide_7_title": "Track your growth",
            "how_to_use_slide_7_desc": "See how many seeds you plant and track your progress day by day.",
            "how_to_use_slide_8_title": "Practice together",
            "how_to_use_slide_8_desc": "Join a group and see what your karma partners are doing.",
            "how_to_use_slide_9_title": "Your altar anywhere",
            "how_to_use_slide_9_desc": "Keep photos of your teacher, family, and inspirations always with you.",
            "rejoy_deep": "Rejoy Deep",
            "upgrade_to_rejoy_deep": "Upgrade to Rejoy Deep",
            "deep_upgrade_title": "Rejoy Deep",
            "deep_upgrade_description": "Rejoy Deep unlocks deeper personal practice tools.",
            "deep_benefits_altar": "Personal Altar",
            "deep_benefits_future": "Future advanced features",
            "deep_benefits_enhanced": "Enhanced experience inside Rejoy",
            "deep_price_monthly": "$5.99 / month",
            "activate_deep": "Activate Deep",
            "altar_title": "Altar",
            "add_portrait_of_teacher": "Add a portrait of your teacher",
            "add_portrait": "Add Portrait",
            "add_photo_or_video": "Add Photo or Video",
            "change_portrait": "Change Portrait",
            "display_name": "Display name",
            "display_name_placeholder": "Your name",
        ],
        "ru": [
            "seeds": "Семена",
            "rejoy_button_hint_title": "Что такое Rejoy?",
            "rejoy_button_hint_body": "Эта кнопка активирует ваши семена. До нажатия вы их только создали. Нажмите Rejoy, чтобы активировать их.",
            "rejoy_button_hint_got_it": "Понятно",
            "seeds_for": "Семена за",
            "seeds_planted": "семян посажено",
            "today": "Сегодня",
            "total": "Всего",
            "yesterday": "Вчера",
            "choose_day": "Выбрать день",
            "done": "Готово",
            "today_timeline": "Сегодняшняя активность",
            "yesterday_timeline": "Вчерашняя активность",
            "timeline": "Активность",
            "no_sessions": "Пока нет сессий. Нажмите Старт, чтобы начать.",
            "no_sessions_day": "Нет сессий в этот день.",
            "empty_state_title": "Ваша хронология готова",
            "empty_state_subtitle": "Нажмите оранжевую кнопку ниже, чтобы начать первую активность",
            "rejoy": "Rejoy",
            "rejoyed": "Rejoyed",
            "rejoyed_exclamation": "rejoyed!",
            "ongoing": "В процессе",
            "activity": "Активность",
            "activity_meditation": "Медитация",
            "activity_yoga": "Йога",
            "activity_walking": "Ходьба",
            "activity_running": "Бег",
            "activity_work": "Работа",
            "activity_cooking": "Готовка",
            "activity_reading": "Чтение",
            "activity_family": "Семья",
            "activity_study": "Учёба",
            "seeds_count": "%d семян",
            "seeds_count_formatted": "%@ семян",
            "share_activity": "Поделиться активностью",
            "share_to": "Поделиться в",
            "save_image": "Сохранить",
            "copy_image": "Копировать",
            "copied": "Скопировано",
            "copy_sticker_hint": "Изображение будет скопировано с прозрачным фоном. Оно окажется в буфере обмена — откройте любой мессенджер или приложение и вставьте.",
            "more": "Ещё",
            "close": "Закрыть",
            "photo_library_required": "Доступ к фото",
            "photo_library_required_message": "Разрешите доступ для сохранения стикера в фото.",
            "settings": "Настройки",
            "permissions": "Разрешения",
            "app_language": "Язык приложения",
            "language": "Язык",
            "language_description": "Выберите язык интерфейса приложения.",
            "recognition_language": "Язык распознавания",
            "voice": "Голос",
            "voice_footer": "Выберите язык, на котором вы говорите при записи посвящения. Выберите русский явно, если автоматическое распознавание работает некорректно.",
            "automatic_russian": "Авто (русский приоритет)",
            "russian": "Русский",
            "english": "Английский",
            "ukrainian": "Украинский",
            "seeds_per_second": "Семян в секунду",
            "seeds_stats": "Статистика семян",
            "total_seeds": "Всего семян",
            "month_seeds_format": "Семян за %@",
            "monthly_seeds_planted": "Семян посажено за месяц",
            "seeds_for_month_year_format": "Семян за %@",
            "time_for_meditation": "Время для медитации",
            "how_to_meditate": "Как делать медитацию?",
            "default": "По умолчанию",
            "activity_types": "Типы активностей",
            "add_activity": "Добавить активность",
            "edit_activity": "Редактировать активность",
            "restore_activity": "Восстановить",
            "delete_activity_confirm": "Удалить эту активность?",
            "about": "О приложении",
            "version": "Версия 1.0",
            "about_description": "Отслеживайте практику. Сажайте семена с каждым моментом посвящения.",
            "microphone": "Микрофон",
            "record_voice": "Запись голосовых посвящений",
            "speech_recognition": "Распознавание речи",
            "transcribe_dedication": "Транскрипция посвящения",
            "notifications": "Уведомления",
            "daily_reminder": "Ежедневное напоминание",
            "notifications_nudges_message": "Получать подталкивания от друзей и ежедневные напоминания",
            "enable": "Включить",
            "enabled": "Включено",
            "denied": "Отклонено",
            "not_set": "Не задано",
            "unknown": "Неизвестно",
            "open_settings": "Открыть настройки",
            "notifications_required": "Требуются уведомления",
            "notifications_required_message": "Разрешите уведомления в Настройки > Rejoy > Уведомления, чтобы работал будильник медитации.",
            "permissions_intro": "Включите для лучшего опыта. Можно изменить позже в настройках.",
            "skip_for_now": "Пропустить",
            "continue_as_guest": "Продолжить как гость",
            "sign_in_with_apple": "Войти через Apple",
            "login_legal_markdown": "Продолжая использовать Rejoy, вы соглашаетесь с [**условиями использования**](%@) и подтверждаете, что ознакомились с [**политикой конфиденциальности**](%@).",
            "watch_stories_again": "Смотреть истории снова",
            "replay_intro": "Показать вступление снова",
            "rej": "Rejoy",
            "start_activity": "Начать активность",
            "cancel": "Отмена",
            "error": "Ошибка",
            "dedication": "Посвящение",
            "dedication_default": "Пусть это посвящение принесёт пользу всем существам.",
            "record_dedication": "Запишите посвящение",
            "save_seeds": "Сохранить семена",
            "microphone_unavailable": "Микрофон или голос недоступны",
            "type_dedication": "Введите посвящение ниже",
            "tap_to_record": "Нажмите для записи",
            "tap_to_stop": "Нажмите для остановки",
            "adjust_duration": "Изменить длительность",
            "adjust_duration_hint": "Добавьте или уберите минуты ниже",
            "duration_adjust_min": "- %d мин",
            "duration_adjust_plus": "+ %d мин",
            "session": "Сессия",
            "delete_session": "Удалить сессию",
            "delete_activity": "Удалить активность",
            "cannot_undo": "Это действие нельзя отменить.",
            "delete": "Удалить",
            "name": "Название",
            "icon": "Иконка",
            "save": "Сохранить",
            "next": "Далее",
            "save_changes": "Сохранить изменения",
            "time": "Время",
            "delete_session_confirm": "Удалить сессию?",
            "pause": "Пауза",
            "resume": "Продолжить",
            "stop": "Стоп",
            "seeds_planted_count": "%d семян посажено",
            "duration_min": "%dмин",
            "duration_h": "%dч",
            "duration_h_min": "%dч %dмин",
            "rejoy_meditation_time": "Rejoy Медитация",
            "rejoy_meditation_enable": "Включить",
            "rejoy_meditation_description": "Установите ежедневное время для Rejoy медитации. Разрешите уведомления при запросе. Кнопки Rejoy разблокируются после этого времени.",
            "rejoy_meditation_prompt_title": "Установите время Rejoy",
            "rejoy_meditation_prompt_subtitle": "Разблокируйте кнопки Rejoy после ежедневной медитации. Нажмите, чтобы настроить.",
            "test_notification": "Тест уведомления (через 5 сек)",
            "accumulating_potential": "Накопление...",
            "ready_at": "Готово в %@",
            "rejoy_in_h": "Rejoy через %dч",
            "rejoy_in_m": "Rejoy через %dмин",
            "accumulating_explanation_title": "Rejoy разблокируется после медитации",
            "accumulating_explanation_body": "Кнопки Rejoy разблокируются после вашего ежедневного времени медитации. Изменить время можно в настройках.",
            "rejoy_button": "Rejoy",
            "accumulating_sheet_title": "Разблокируется после Rejoy медитации",
            "accumulating_sheet_unlock_after": "после вашей Rejoy медитации",
            "accumulating_sheet_explainer": "Rejoy — это тактильный способ завершить свои добрые дела одно за другим. После Rejoy медитации нажмите каждую сессию, чтобы ещё раз вспомнить всё хорошее и почувствовать радость в конце дня.",
            "understood": "Понятно",
            "unlock_in_h": "через %dч",
            "unlock_in_h_m": "через %dч %dмин",
            "unlock_in_m": "через %dмин",
            "rejoy_meditation_carousel_title": "Rejoy Медитация",
            "rejoy_meditation_slide_1_title": "Вспомните свои добрые дела.",
            "rejoy_meditation_slide_1_desc": "Прокрутите в голове все хорошие поступки и моменты заботы, которые вы проявили за сегодняшний день.",
            "rejoy_meditation_slide_2_title": "Почувствуйте круги влияния.",
            "rejoy_meditation_slide_2_desc": "Представьте радость людей, которым вы помогли, и как их настроение передается другим.",
            "rejoy_meditation_slide_3_title": "Осознайте свою щедрость.",
            "rejoy_meditation_slide_3_desc": "Вспомните, как вы делились своим временем, вниманием, поддержкой или оказывали помощь.",
            "rejoy_meditation_slide_4_title": "Практика благодарности.",
            "rejoy_meditation_slide_4_desc": "Поблагодарите мир за саму жизнь, близких людей, ваши возможности и простые блага.",
            "rejoy_meditation_slide_5_title": "Время расцветать.",
            "rejoy_meditation_slide_5_desc": "Почувствуйте, как радость активирует ваши добрые поступки, поливая их, словно ухоженный сад.",
            "learn_more_rejoy_meditation": "Как делать медитацию?",
            "skip": "Пропустить",
            "sangha": "Группа",
            "create_sangha": "Создать группу",
            "join_sangha": "Присоединиться к группе",
            "join_by_code": "Войти по коду",
            "sangha_name": "Название группы",
            "invite_code": "Код приглашения",
            "invite": "Пригласить",
            "invite_members": "Пригласить участников",
            "invite_link_description": "Поделитесь ссылкой, чтобы другие могли присоединиться",
            "invite_message": "Присоединяйся к моей группе в Rejoy!\n\n1. Открой Rejoy и перейди в Профиль → Настройки\n2. Нажми «Видимость и группы»\n3. Включи переключатель и введи этот код:\n\n%@",
            "join_sangha_code_hint": "Введи 6-символьный код, который тебе передал участник группы.",
            "profile_visibility": "Видимость и группы",
            "private": "Приватно",
            "private_profile_description": "Ваша активность не будет видна участникам группы на главном экране. Включите, чтобы делиться прогрессом.",
            "public": "Публично",
            "public_profile": "Публичный профиль",
            "groups": "Группы",
            "group_members_count": "%d участников",
            "profile_visibility_invite_title": "Присоединиться к группе",
            "profile_visibility_invite_description": "Группа позволяет видеть активность друг друга на главном экране. Попроси участника группы 6-символьный код приглашения.",
            "insert_invite_code": "Введите код приглашения",
            "switch_to_private_confirm": "Перейти в приватный режим?",
            "switch_to_private_confirm_message": "Вы будете скрыты от других в группе. Они не увидят вашу активность, пока вы снова не включите видимость.",
            "invite_to_group": "Пригласить в группу",
            "pause_my_visibility": "Приостановить видимость",
            "leave_group": "Выйти из группы",
            "leave_group_confirm": "Выйти из группы?",
            "leave_group_confirm_message": "Вы будете удалены из группы. Можете присоединиться снова в любое время по коду приглашения.",
            "active_now": "Сейчас активен",
            "karma_partners": "Карма-партнёры",
            "seeds_accumulating": "накопление",
            "sangha_empty_state": "Присоединитесь к группе, чтобы видеть активность других",
            "push_to_activity_button": "Дай лёгкий толчок",
            "partner": "Партнер",
            "nudge_permission_prompt_title": "Получать подталкивания от друзей",
            "nudge_permission_prompt_message": "Включите уведомления, чтобы получать подталкивания, когда вы не в приложении.",
            "nudge_sent": "Подтолкнули!",
            "nudge_notification_title": "%@ болеет за тебя!",
            "nudge_notification_subtitle": "Начни активность, чтобы посадить семена.",
            "continue": "Продолжить",
            "account": "Аккаунт",
            "log_out": "Выйти",
            "log_out_confirm": "Выйти?",
            "log_out_confirm_message": "Локальные данные сохранятся. Вы можете войти снова в любое время.",
            "achievement_save": "Понятно",
            "achievement_unlocked_on": "Разблокировано",
            "achievement_section_title": "Награды",
            "achievement_empty_state": "Нажмите все кнопки Rejoy, чтобы разблокировать награды",
            "rewards_view_all": "Все",
            "rewards_gallery_title": "Все награды",
            "rewards_achieved_progress": "Получено %1$lld из %2$lld",
            "rewards_explainer_title": "Как работают награды",
            "rewards_explainer_body": "Завершайте день: нажимайте Rejoy у каждой активности, когда закончили. Раз в день одна награда может открыться случайным образом, когда вы выполните все Rejoy. Коллекция растёт со временем — продолжайте завершать активности и отмечать их Rejoy, чтобы собрать все значки. Дата под значком — когда вы в последний раз разблокировали его на этом устройстве.",
            "share_app": "Поделиться Rejoy",
            "share_app_message": "Привет! Присоединяйся к Rejoy! Отслеживай медитацию и осознанность. Сажай семена с каждым моментом практики. Попробуй бета-версию:",
            "share_app_message_with_seeds": "Привет! Вот сколько семян собралось у меня в этом месяце: %@ 🌱\nПрисоединяйся к Rejoy, попробуй бета-версию:\n",
            "seeds_field_empty": "Сади семена медитацией",
            "what_is_seeds": "Что такое семена?",
            "what_is_seeds_explainer": "Узнайте, как ментальные отпечатки накапливаются и формируют реальность. На основе буддийской психологии и «Огранщика алмаза».",
            "seeds_info_slide_1_title": "Ментальные отпечатки.",
            "seeds_info_slide_1_desc": "Каждый момент опыта сажает «семена» в подсознание. Эти отпечатки никогда не нейтральны — они накапливаются и формируют то, как вы воспринимаете мир и что жизнь вам приносит.",
            "seeds_info_slide_2_title": "65 семян в секунду.",
            "seeds_info_slide_2_desc": "Согласно буддийским текстам (Абхидхармакоша), ум обрабатывает около %@ ментальных мгновений в секунду. Каждый момент внимания оставляет отпечаток. Важно, на чём вы фокусируетесь.",
            "seeds_info_slide_3_title": "Они быстро накапливаются.",
            "seeds_info_slide_3_desc": "В минуту: %@ семян. В час: %@. За полный день: %@. Ваши ежедневные действия создают огромное поле причин, которые принесут плоды в будущем.",
            "seeds_info_slide_4_title": "Семена формируют реальность.",
            "seeds_info_slide_4_desc": "Как белый экран, реальность нейтральна. Ваши прошлые семена проецируются на неё. Добрые дела сажают добрые семена — для изобилия, здоровья, гармонии. То, что вы делаете сегодня, станет завтрашним опытом.",
            "seeds_info_slide_5_title": "Поливайте семена.",
            "seeds_info_slide_5_desc": "Вечерняя Rejoy медитация «поливает» ваши добрые семена радостью. Это запечатывает их и помогает им расти. Маленькое доброе дело, вспомненное с радостью, удваивается в силе каждый день.",
            "unfinished_rejoy_reminder_title": "Ваши семена со вчера ждут",
            "unfinished_rejoy_reminder_body": "Вы завершили вчера несколько активностей. Нажмите Rejoy, чтобы полить эти семена и почувствовать радость от того, что вы сделали.",
            "unfinished_rejoy_reminder_action": "Rejoy сейчас",
            "unfinished_rejoy_reminder_skip": "Позже",
            "how_to_use_rejoy": "Как пользоваться Rejoy?",
            "how_to_use_rejoy_explainer": "Краткое руководство: отслеживайте активности, активируйте семена и делитесь прогрессом.",
            "how_to_use_slide_1_title": "Начни активность",
            "how_to_use_slide_1_desc": "Нажмите кнопку и выберите занятие — медитация, йога, работа или семья.",
            "how_to_use_slide_2_title": "Семена растут",
            "how_to_use_slide_2_desc": "Каждая секунда твоего действия создаёт кармические семена.",
            "how_to_use_slide_3_title": "Придай смысл",
            "how_to_use_slide_3_desc": "После завершения запиши посвящение и придай своему действию более глубокий смысл.",
            "how_to_use_slide_4_title": "Установи время Rejoy",
            "how_to_use_slide_4_desc": "Выбери, когда семена активируются через медитацию.",
            "how_to_use_slide_5_title": "Активируй семена",
            "how_to_use_slide_5_desc": "Сделай Rejoy для активности, чтобы семена стали зелёными.",
            "how_to_use_slide_6_title": "Делись практикой",
            "how_to_use_slide_6_desc": "Создавай красивые бейджи и делись своими действиями с друзьями.",
            "how_to_use_slide_7_title": "Следи за ростом",
            "how_to_use_slide_7_desc": "Смотрите, сколько семян вы сеете, и отслеживайте свой прогресс день за днём.",
            "how_to_use_slide_8_title": "Практикуйте вместе",
            "how_to_use_slide_8_desc": "Присоединяйся к группе и смотри, что делают твои карма-партнёры.",
            "how_to_use_slide_9_title": "Алтарь всегда рядом",
            "how_to_use_slide_9_desc": "Храни фото учителя, семьи и вдохновения всегда с собой.",
            "rejoy_deep": "Rejoy Deep",
            "upgrade_to_rejoy_deep": "Перейти на Rejoy Deep",
            "deep_upgrade_title": "Rejoy Deep",
            "deep_upgrade_description": "Rejoy Deep открывает инструменты для более глубокой личной практики.",
            "deep_benefits_altar": "Личный Алтарь",
            "deep_benefits_future": "Будущие расширенные функции",
            "deep_benefits_enhanced": "Улучшенный опыт в Rejoy",
            "deep_price_monthly": "$5.99 / месяц",
            "activate_deep": "Активировать Deep",
            "altar_title": "Алтарь",
            "add_portrait_of_teacher": "Добавьте портрет вашего учителя",
            "add_portrait": "Добавить портрет",
            "add_photo_or_video": "Добавить фото или видео",
            "change_portrait": "Изменить портрет",
            "display_name": "Имя",
            "display_name_placeholder": "Ваше имя",
        ],
        "uk": [
            "seeds": "Зерна",
            "rejoy_button_hint_title": "Що таке Rejoy?",
            "rejoy_button_hint_body": "Ця кнопка активує ваші зерна. До натискання ви їх лише створили. Натисніть Rejoy, щоб активувати їх.",
            "rejoy_button_hint_got_it": "Зрозуміло",
            "seeds_for": "Зерна за",
            "seeds_planted": "зерен посаджено",
            "today": "Сьогодні",
            "total": "Всього",
            "yesterday": "Вчора",
            "choose_day": "Обрати день",
            "done": "Готово",
            "today_timeline": "Сьогоднішня активність",
            "yesterday_timeline": "Вчорашня активність",
            "timeline": "Активність",
            "no_sessions": "Поки немає сесій. Натисніть Старт, щоб почати.",
            "no_sessions_day": "Немає сесій у цей день.",
            "empty_state_title": "Ваша хроніка готова",
            "empty_state_subtitle": "Натисніть помаранчеву кнопку внизу, щоб почати першу активність",
            "rejoy": "Rejoy",
            "rejoyed": "Rejoyed",
            "rejoyed_exclamation": "rejoyed!",
            "ongoing": "В процесі",
            "activity": "Активність",
            "activity_meditation": "Медитація",
            "activity_yoga": "Йога",
            "activity_walking": "Ходьба",
            "activity_running": "Біг",
            "activity_work": "Робота",
            "activity_cooking": "Готування",
            "activity_reading": "Читання",
            "activity_family": "Сім'я",
            "activity_study": "Навчання",
            "seeds_count": "%d зерен",
            "seeds_count_formatted": "%@ зерен",
            "share_activity": "Поділитися активністю",
            "share_to": "Поділитися в",
            "save_image": "Зберегти",
            "copy_image": "Копіювати",
            "copied": "Скопійовано",
            "copy_sticker_hint": "Зображення буде скопійовано з прозорим фоном. Воно опиниться в буфері обміну — відкрийте будь-який месенджер або програму та вставте.",
            "more": "Ще",
            "close": "Закрити",
            "photo_library_required": "Доступ до фото",
            "photo_library_required_message": "Дозвольте доступ для збереження стікера в фото.",
            "settings": "Налаштування",
            "profile": "Профіль",
            "permissions": "Дозволи",
            "app_language": "Мова додатку",
            "language": "Мова",
            "language_description": "Оберіть мову інтерфейсу додатку.",
            "recognition_language": "Мова розпізнавання",
            "voice": "Голос",
            "voice_footer": "Оберіть мову, якою ви говорите при записі присвячення. Оберіть українську або російську явно, якщо автоматичне розпізнавання працює некоректно.",
            "automatic_russian": "Авто (російська пріоритет)",
            "russian": "Русский",
            "english": "English",
            "ukrainian": "Українська",
            "seeds_per_second": "Зерен в секунду",
            "seeds_this_month": "Зерен за місяць",
            "seeds_stats": "Статистика зерен",
            "total_seeds": "Всього зерен",
            "month_seeds_format": "Зерен за %@",
            "monthly_seeds_planted": "Зерен посаджено за місяць",
            "seeds_for_month_year_format": "Зерен за %@",
            "time_for_meditation": "Час для медитації",
            "how_to_meditate": "Як робити медитацію?",
            "seeds_description": "Кожну секунду присвячення створюються причини («зерна»), які несуться вперед. Жодна ваша дія не буває нейтральною.",
            "default": "За замовчуванням",
            "activity_types": "Типи активностей",
            "add_activity": "Додати активність",
            "edit_activity": "Редагувати активність",
            "restore_activity": "Відновити",
            "delete_activity_confirm": "Видалити цю активність?",
            "about": "Про додаток",
            "version": "Версія 1.0",
            "about_description": "Відстежуйте практику. Садіть зерна з кожним моментом присвячення.",
            "microphone": "Мікрофон",
            "record_voice": "Запис голосових присвячень",
            "speech_recognition": "Розпізнавання мовлення",
            "transcribe_dedication": "Транскрипція присвячення",
            "notifications": "Сповіщення",
            "daily_reminder": "Щоденне нагадування",
            "notifications_nudges_message": "Отримувати підштовхування від друзів та щоденні нагадування",
            "enable": "Увімкнути",
            "enabled": "Увімкнено",
            "denied": "Відхилено",
            "not_set": "Не встановлено",
            "unknown": "Невідомо",
            "open_settings": "Відкрити налаштування",
            "notifications_required": "Потрібні сповіщення",
            "notifications_required_message": "Дозвольте сповіщення в Налаштування > Rejoy > Сповіщення, щоб працював будильник медитації.",
            "permissions_intro": "Увімкніть для кращого досвіду. Можна змінити пізніше в налаштуваннях.",
            "skip_for_now": "Пропустити",
            "continue_as_guest": "Продовжити як гість",
            "sign_in_with_apple": "Увійти через Apple",
            "login_legal_markdown": "Продовжуючи використовувати Rejoy, ви погоджуєтеся з [**умовами використання**](%@) і підтверджуєте, що ознайомилися з [**політикою конфіденційності**](%@).",
            "watch_stories_again": "Переглянути історії знову",
            "replay_intro": "Показати вступ знову",
            "rej": "Rejoy",
            "start_activity": "Почати активність",
            "cancel": "Скасувати",
            "error": "Помилка",
            "dedication": "Присвячення",
            "dedication_default": "Нехай це присвячення принесе користь усім істотам.",
            "record_dedication": "Запишіть присвячення",
            "save_seeds": "Зберегти зерна",
            "microphone_unavailable": "Мікрофон або голос недоступні",
            "type_dedication": "Введіть присвячення нижче",
            "tap_to_record": "Натисніть для запису",
            "tap_to_stop": "Натисніть для зупинки",
            "adjust_duration": "Змінити тривалість",
            "adjust_duration_hint": "Додайте або заберіть хвилини нижче",
            "duration_adjust_min": "- %d хв",
            "duration_adjust_plus": "+ %d хв",
            "session": "Сесія",
            "delete_session": "Видалити сесію",
            "delete_activity": "Видалити активність",
            "cannot_undo": "Цю дію не можна скасувати.",
            "delete": "Видалити",
            "name": "Назва",
            "icon": "Іконка",
            "save": "Зберегти",
            "next": "Далі",
            "save_changes": "Зберегти зміни",
            "time": "Час",
            "delete_session_confirm": "Видалити сесію?",
            "pause": "Пауза",
            "resume": "Продовжити",
            "stop": "Стоп",
            "seeds_planted_count": "%d зерен посаджено",
            "duration_min": "%dхв",
            "duration_h": "%dгод",
            "duration_h_min": "%dгод %dхв",
            "rejoy_meditation_time": "Rejoy Медитація",
            "rejoy_meditation_enable": "Увімкнути",
            "rejoy_meditation_description": "Встановіть щоденний час для Rejoy медитації. Дозвольте сповіщення при запиті. Кнопки Rejoy розблоковуються після цього часу.",
            "rejoy_meditation_prompt_title": "Встановіть час Rejoy",
            "rejoy_meditation_prompt_subtitle": "Розблокуйте кнопки Rejoy після щоденної медитації. Натисніть, щоб налаштувати.",
            "test_notification": "Тест сповіщення (через 5 сек)",
            "accumulating_potential": "Накопичення...",
            "ready_at": "Готово о %@",
            "rejoy_in_h": "Rejoy через %dгод",
            "rejoy_in_m": "Rejoy через %dхв",
            "accumulating_explanation_title": "Rejoy розблоковується після медитації",
            "accumulating_explanation_body": "Кнопки Rejoy розблоковуються після вашого щоденного часу медитації. Змінити час можна в налаштуваннях.",
            "rejoy_button": "Rejoy",
            "accumulating_sheet_title": "Розблокується після Rejoy медитації",
            "accumulating_sheet_explainer": "Rejoy — це тактильний спосіб завершити свої добрі справи одну за одною. Після Rejoy медитації натисніть кожну сесію, щоб ще раз згадати все добре і відчути радість наприкінці дня.",
            "understood": "Зрозуміло",
            "unlock_in_h": "через %dгод",
            "unlock_in_h_m": "через %dгод %dхв",
            "unlock_in_m": "через %dхв",
            "rejoy_meditation_carousel_title": "Rejoy Медитація",
            "rejoy_meditation_slide_1_title": "Згадайте свої добрі справи.",
            "rejoy_meditation_slide_1_desc": "Прокрутіть у голові всі хороші вчинки та моменти турботи, які ви виявили за сьогоднішній день.",
            "rejoy_meditation_slide_2_title": "Відчуйте кола впливу.",
            "rejoy_meditation_slide_2_desc": "Уявіть радість людей, яким ви допомогли, і як їхній настрій передається іншим.",
            "rejoy_meditation_slide_3_title": "Усвідомте свою щедрість.",
            "rejoy_meditation_slide_3_desc": "Згадайте, як ви ділилися своїм часом, увагою, підтримкою або надавали допомогу.",
            "rejoy_meditation_slide_4_title": "Практика вдячності.",
            "rejoy_meditation_slide_4_desc": "Подякуйте світу за саме життя, близьких людей, ваші можливості та прості блага.",
            "rejoy_meditation_slide_5_title": "Час розквітати.",
            "rejoy_meditation_slide_5_desc": "Відчуйте, як радість активує ваші добрі вчинки, поливаючи їх, немов доглянутий сад.",
            "learn_more_rejoy_meditation": "Як робити медитацію?",
            "skip": "Пропустити",
            "sangha": "Група",
            "create_sangha": "Створити групу",
            "join_sangha": "Приєднатися до групи",
            "join_by_code": "Увійти за кодом",
            "sangha_name": "Назва групи",
            "invite_code": "Код запрошення",
            "invite": "Запросити",
            "invite_members": "Запросити учасників",
            "invite_link_description": "Поділіться посиланням, щоб інші могли приєднатися",
            "invite_message": "Приєднуйся до моєї групи в Rejoy!\n\n1. Відкрий Rejoy і перейди в Профіль → Налаштування\n2. Натисни «Видимість і групи»\n3. Увімкни перемикач і введи цей код:\n\n%@",
            "join_sangha_code_hint": "Введи 6-символьний код, який тобі передав учасник групи.",
            "profile_visibility": "Видимість і групи",
            "private": "Приватно",
            "private_profile_description": "Ваша активність не буде видна учасникам групи на головному екрані. Увімкніть, щоб ділитися прогресом.",
            "public": "Публічно",
            "public_profile": "Публічний профіль",
            "groups": "Групи",
            "group_members_count": "%d учасників",
            "profile_visibility_invite_title": "Приєднатися до групи",
            "profile_visibility_invite_description": "Група дозволяє бачити активність один одного на головному екрані. Попроси учасника групи 6-символьний код запрошення.",
            "insert_invite_code": "Введіть код запрошення",
            "switch_to_private_confirm": "Перейти в приватний режим?",
            "switch_to_private_confirm_message": "Ви будете приховані від інших у групі. Вони не побачать вашу активність, поки ви знову не увімкнете видимість.",
            "invite_to_group": "Запросити до групи",
            "pause_my_visibility": "Призупинити видимість",
            "leave_group": "Вийти з групи",
            "leave_group_confirm": "Вийти з групи?",
            "leave_group_confirm_message": "Вас буде видалено з групи. Можете приєднатися знову в будь-який час за кодом запрошення.",
            "active_now": "Зараз активний",
            "karma_partners": "Карма-партнери",
            "seeds_accumulating": "накопичення",
            "sangha_empty_state": "Приєднайтеся до групи, щоб бачити активність інших",
            "push_to_activity_button": "Дай легкий поштовх",
            "partner": "Партнер",
            "nudge_permission_prompt_title": "Отримувати підштовхування від друзів",
            "nudge_permission_prompt_message": "Увімкніть сповіщення, щоб отримувати підштовхування, коли ви не в додатку.",
            "nudge_sent": "Підштовхнули!",
            "nudge_notification_title": "%@ вболіває за тебе!",
            "nudge_notification_subtitle": "Почни активність, щоб посадити насіння.",
            "continue": "Продовжити",
            "account": "Обліковий запис",
            "log_out": "Вийти",
            "log_out_confirm": "Вийти?",
            "log_out_confirm_message": "Локальні дані збережуться. Ви можете увійти знову в будь-який час.",
            "achievement_save": "Зрозуміло",
            "achievement_unlocked": "Розблоковано!",
            "achievement_unlocked_on": "Розблоковано",
            "achievement_section_title": "Нагороди",
            "achievement_empty_state": "Натисніть усі кнопки Rejoy, щоб розблокувати нагороди",
            "rewards_view_all": "Усі",
            "rewards_gallery_title": "Усі нагороди",
            "rewards_achieved_progress": "Отримано %1$lld з %2$lld",
            "rewards_explainer_title": "Як працюють нагороди",
            "rewards_explainer_body": "Завершуйте день: натискайте Rejoy біля кожної активності, коли закінчите. Раз на день одна нагорода може відкритися випадково, коли ви виконаєте всі Rejoy. Колекція зростає з часом — продовжуйте завершувати активності й відзначати їх Rejoy, щоб зібрати всі значки. Дата під значком — коли ви востаннє розблокували його на цьому пристрої.",
            "rewards_unlock_date_unknown": "Дата недоступна",
            "share_app": "Поділитися Rejoy",
            "share_app_message": "Привіт! Приєднуйся до Rejoy! Відстежуй медитацію та особистісну практику. Сади зерна з кожним моментом уважності. Спробуй бета-версію:",
            "share_app_message_with_seeds": "Привіт! Ось скільки насіння зібралося в мене цього місяця: %@ 🌱\nПриєднуйся до Rejoy, спробуй бета-версію:\n",
            "seeds_field_empty": "Сади насіння медитацією",
            "what_is_seeds": "Що таке зерна?",
            "what_is_seeds_explainer": "Дізнайтеся, як ментальні відбитки накопичуються і формують реальність. На основі буддійської психології та «Огранщика алмаза».",
            "seeds_info_slide_1_title": "Ментальні відбитки.",
            "seeds_info_slide_1_desc": "Кожна мить досвіду садить «зерна» в підсвідомість. Ці відбитки ніколи не нейтральні — вони накопичуються і формують те, як ви сприймаєте світ і що життя вам приносить.",
            "seeds_info_slide_2_title": "65 зерен на секунду.",
            "seeds_info_slide_2_desc": "Згідно з буддійськими текстами (Абхідхармакоша), розум обробляє близько %@ ментальних митей на секунду. Кожна мить уваги залишає відбиток. Важливо, на чому ви фокусуєтесь.",
            "seeds_info_slide_3_title": "Вони швидко накопичуються.",
            "seeds_info_slide_3_desc": "За хвилину: %@ зерен. За годину: %@. За повний день: %@. Ваші щоденні дії створюють величезне поле причин, які принесуть плоди в майбутньому.",
            "seeds_info_slide_4_title": "Зерна формують реальність.",
            "seeds_info_slide_4_desc": "Як білий екран, реальність нейтральна. Ваші минулі зерна проектуються на неї. Добрі справи садять добрі зерна — для достатку, здоров'я, гармонії. Те, що ви робите сьогодні, стане завтрашнім досвідом.",
            "seeds_info_slide_5_title": "Поливайте зерна.",
            "seeds_info_slide_5_desc": "Вечірня Rejoy медитація «поливає» ваші добрі зерна радістю. Це запечатує їх і допомагає їм рости. Маленька добра справа, згадана з радістю, подвоюється в силі щодня.",
            "unfinished_rejoy_reminder_title": "Ваші зерна з вчора чекають",
            "unfinished_rejoy_reminder_body": "Ви завершили вчора кілька активностей. Натисніть Rejoy, щоб полити ці зерна і відчути радість від того, що ви зробили.",
            "unfinished_rejoy_reminder_action": "Rejoy зараз",
            "unfinished_rejoy_reminder_skip": "Пізніше",
            "how_to_use_rejoy": "Як користуватися Rejoy?",
            "how_to_use_rejoy_explainer": "Короткий посібник: відстежуйте активності, активуйте зерна та діліться прогресом.",
            "how_to_use_slide_1_title": "Почни активність",
            "how_to_use_slide_1_desc": "Натисніть кнопку та оберіть заняття — медитація, йога, робота або сім'я.",
            "how_to_use_slide_2_title": "Насіння росте",
            "how_to_use_slide_2_desc": "Кожна секунда твоєї дії створює кармічне насіння.",
            "how_to_use_slide_3_title": "Надай сенс",
            "how_to_use_slide_3_desc": "Після завершення запиши коротке присвячення та надай своїй дії глибший сенс.",
            "how_to_use_slide_4_title": "Встанови час Rejoy",
            "how_to_use_slide_4_desc": "Обери, коли твоє насіння активується через медитацію.",
            "how_to_use_slide_5_title": "Активуй насіння",
            "how_to_use_slide_5_desc": "Rejoy свої дії, щоб насіння стало зеленим.",
            "how_to_use_slide_6_title": "Ділись практикою",
            "how_to_use_slide_6_desc": "Створюй красиві бейджі та ділись своїми діями з друзями.",
            "how_to_use_slide_7_title": "Відстежуй розвиток",
            "how_to_use_slide_7_desc": "Дивіться, скільки насіння ви сієте, і відстежуйте свій прогрес день за днем.",
            "how_to_use_slide_8_title": "Практикуйте разом",
            "how_to_use_slide_8_desc": "Приєднуйся до групи та бач, що роблять твої карма-партнери.",
            "how_to_use_slide_9_title": "Твій вівтар завжди поруч",
            "how_to_use_slide_9_desc": "Зберігай фото вчителя, родини та натхнення поруч із собою.",
            "rejoy_deep": "Rejoy Deep",
            "upgrade_to_rejoy_deep": "Оновити до Rejoy Deep",
            "deep_upgrade_title": "Rejoy Deep",
            "deep_upgrade_description": "Rejoy Deep відкриває інструменти для глибшої особистої практики.",
            "deep_benefits_altar": "Особистий Вівтар",
            "deep_benefits_future": "Майбутні розширені функції",
            "deep_benefits_enhanced": "Покращений досвід у Rejoy",
            "deep_price_monthly": "$5.99 / місяць",
            "activate_deep": "Активувати Deep",
            "altar_title": "Вівтар",
            "add_portrait_of_teacher": "Додайте портрет вашого вчителя",
            "add_portrait": "Додати портрет",
            "add_photo_or_video": "Додати фото або відео",
            "change_portrait": "Змінити портрет",
            "display_name": "Ім'я",
            "display_name_placeholder": "Ваше ім'я",
        ]
    ]
}
